{'name': 'Ubicacion de Productos',
 'description': 'Modelo para guardar ubicaciones de productos ',
 'author': 'Jonatan Rodriguez',
 'depends': ['base', 'stock', 'sale_management', 'account','taller','sale_margin_security'],
 'data': [
    'security/ubicacion_security.xml',
    'security/ir.model.access.csv',
    'views/ubicacion_menu.xml',
    'views/ubicacion_view.xml',
    'views/product_template_view.xml',
    'views/ubicacion_list_template.xml',
    'views/sale_order_line_view.xml',
    #'views/sale_order_view.xml',
    'views/ubicacion_category_view.xml',
    #'views/account_invoice_view.xml',
    #'views/account_journal_view.xml',
    'reports/ubicacion_report.xml',
    'reports/ubicacion_sql_report.xml',
    #'wizard/account_invoice_refund_view.xml',
 ],
 'demo': [
    #'data/res.partner.csv',
    'data/ubicacion.book.csv',
    'data/ubicacion_demo.xml',
 ],
 'application': True,
 'installable': True,
}
